CREATE TABLE `t_plugin` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
	`name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '插件名称',
	`state` TINYINT NOT NULL DEFAULT '0' COMMENT '状态 1：开启 0：关闭',
	`remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '描述',
	`version` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '版本',
	`author` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '作者',
	`file_path` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '本地路径',
	`create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
	PRIMARY KEY (`id`),
	UNIQUE INDEX `uni_name` (`name`)
)
COMMENT='插件'
ENGINE=InnoDB
;
